baseURL = "https://your-domain.com/"
languageCode = "en-us"
title = "Kurt O. Laguerta"
theme = "careercanvas"

enableEmoji = true

[params]
  name = "Kurt O. Laguerta"
  tagline = "Software Engineer, Web Developer"
  location = "1921 B Dagonoy San Andres Bukid Manila"
  description = "Full-stack developer with over 5 years of experience in building scalable web applications and supporting IT operations. Skilled in C#, .NET Framework, Java, and Spring Boot, with practical experience in microservice-based architecture. Contributed to the development of a government health information system focused on citizen registration and delivery of digital health services. Also experienced in IT infrastructure maintenance, PhilHealth claims encoding, and image/video editing."

  email = "laguertakurt@gmail.com"
  phone = "+639610538041"
  image = "/images/kurt.jpg"
  og_image = "/images/kurt.jpg"
  author = "Kurt O. Laguerta"

  linkedin_url = "https://www.linkedin.com/in/kurt-laguerta-70a951347"
  linkedin_text = "kurt-laguerta"
  github_url = "https://https://github.com/KurtLaguerta"
  github_text = "KurtLaguerta"

  hero_description = "I specialize in building robust full-stack web applications with clean code and modern UI. Let’s build something amazing together!"
  hero_location = "1921 B Dagonoy San Andres Bukid Manila"
  profile_image = "/images/kurt.jpg"  # or your preferred portrait image

  resume_url_en = "/files/kurt-laguerta-resume.pdf"
  resume_label = "Download Resume"

  copyright = "© 2025 Kurt O. Laguerta. All rights reserved."

  collab_tags = [
    "Web Development", "Freelancing", "Open Source", "Tech Consulting", "Remote Work"
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 1
[[menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 2
[[menu.main]]
  name = "Skills"
  url = "#skills"
  weight = 3
[[menu.main]]
  name = "Technical"
  url = "#technical"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5


[[params.social]]
  icon = "linkedin-in"
  url = "https://www.linkedin.com/in/kurt-laguerta-70a951347"

[[params.social]]
  icon = "github"
  url = "https://github.com/KurtLaguerta"
